import React from 'react'

const Home = () => {
    return (
        <div>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus non quasi rerum fugit sunt veritatis, asperiores laborum beatae minus vero alias obcaecati, distinctio exercitationem rem iusto perferendis facilis nihil perspiciatis totam sequi illo. Laborum vero ratione rem sapiente debitis corrupti ab rerum libero repellat, voluptas sed voluptatibus officiis, assumenda error deleniti! Provident maiores consequatur eligendi esse? Ducimus quam omnis vel tempora, et accusamus sint ad nemo libero magni mollitia saepe quo reprehenderit, atque nulla commodi itaque? Id quidem minus atque suscipit perferendis enim exercitationem recusandae! Libero, dolore magnam? Omnis excepturi aliquam quibusdam, harum perspiciatis repudiandae porro ducimus, recusandae magni sint quis, assumenda eum nulla aut? Commodi iste similique earum animi ut soluta corrupti dolorem dignissimos ratione quibusdam facilis dolorum itaque officiis, harum assumenda tempora autem voluptatibus alias neque nobis odit. Commodi recusandae nemo veniam quae autem molestiae sit nulla reprehenderit aliquam mollitia beatae eligendi, quam reiciendis temporibus totam atque incidunt optio ducimus deleniti impedit illo alias, harum provident! Magnam temporibus fugiat asperiores labore, iste quibusdam. Dolore corporis quia id asperiores voluptas reiciendis ullam maxime ipsum fugiat. Ducimus obcaecati nam voluptate quas dolore accusantium cum ratione cumque similique eligendi, iusto quam quisquam vitae, quos, minima quod facere dolorem. Iste, sed! Quos blanditiis ipsa ad incidunt nesciunt cumque, eaque libero! Quasi ab ut consequuntur harum sed eius, facere molestias, dolore, assumenda numquam repellat sint quis possimus est commodi enim at quam quas beatae maxime veritatis neque id tempore necessitatibus! Iusto tempora fugit doloribus deserunt corrupti quo dolore distinctio, omnis atque impedit dolores labore praesentium et beatae quos nesciunt sapiente! Incidunt quam eos atque impedit, harum ipsam exercitationem aperiam eveniet architecto beatae, recusandae doloribus quo doloremque enim aut at eligendi aliquid unde sint temporibus molestias. Ad et consequuntur excepturi nulla eius quis harum fugiat possimus repudiandae id deserunt nostrum, dolorem non, repellat quas.
        </div>
    )
}

export default Home